select
  user_id,
  session_id,
  "time" as session_start_time,
  library,
  platform,
  device,
  device_type,
  carrier,
  app_name,
  app_version,
  country,
  region,
  city,
  ip,
  referrer,
  rtrim(landing_page, '/') as landing_page,
  browser,
  search_keyword,
  nullif(utm_source, '') as utm_source,
  nullif(utm_campaign, '') as utm_campaign,
  nullif(utm_medium, '') as utm_medium,
  nullif(utm_term, '') as utm_term,
  nullif(utm_content, '') as utm_content
from {{var('sessions_table')}}
