select
  user_id,
  session_id,
  "time" as session_start_time,
  library,
  platform,
  device,
  device_type,
  carrier,
  app_name,
  app_version,
  country,
  region,
  city,
  ip,
  referrer,
  rtrim(landing_page, '/') as landing_page,
  browser,
  search_keyword,
  utm_source,
  utm_campaign,
  utm_medium,
  utm_term,
  utm_content
from {{var('sessions_table')}}
